#update_products_count_of_empty:
  #every: 30m
  #class: Topic::TopicQu
  #queue: schedule
  #description: "更新Products count"
#si:
  #every: 19m
  #class: Topic::SmartIndex
  #queue: schedule
  #description: "smart index"
