#update_products_count_of_empty:
  ##cron: "52 * * * *"
  #every: 3m
  #class: Topic::TopicQu
  #queue: schedule
  #description: "更新Products count"
si:
  #cron: "45 * * * *"
  every: 15m
  class: Topic::SmartIndex
  queue: schedule
  description: "smart index"
