update_products_count_of_empty:
  cron: "52 * * * *"
  class: Topic::TopicQu
  queue: schedule
  description: "更新Products count"
si:
  cron: "30 * * * *"
  class: Topic::SmartIndex
  queue: schedule
  description: "smart index"
